### ISSUE TITLE
Configurar ambiente de armazenamento em Data Lake 

### ISSUE THREAD

**Issue by suyane924** [suyane924/TrabalhoFinalEng_Dados#2]
- Estruturar um Data Lake em object storage, utilizando a arquitetura em camadas (Landing, Bronze, Silver, Gold).
- Devem estar no formato Delta Lake ou Apache Iceberg.

**Comment by Guna-ME** [comment]
Estrutura criada com Terraform via Ubuntu; utilizado arquitetura medalhão.
